### ISSUE TITLE
Broken links for f# Freya, WebApi, Frank

### ISSUE THREAD

**Issue by wallymathieu** [TodoBackend/todo-backend-site#174]
The server http://todo-backend-fsharp.azurewebsites.net/ seems to be missing.

**Comment by moredip** [comment]
It's quite likely that the contributor of that implementation is no longer running the site. This does happen with some contributions, unfortunately. 

There's nothing I can really do about it, but you could file an issue with the contributor directly - [this repo](https://github.com/panesofglass/TodoBackendFSharp/issues), I think.
