### ISSUE TITLE
Deployment fails

### ISSUE THREAD

**Issue by jqno** [TodoBackend/todo-backend-site#182]
Hi,

A few weeks ago you merged my PR (#178) for a Todo Backend implementation -- thank you for that!

However, it still hasn't appeared on the website. Possibly because the Codeship build is failing. Unfortunately I'm not able to log in there to see what's going on, so I can't provide further details.

Thought I'd let you know just in case you missed it.

**Comment by moredip** [comment]
Thanks for letting me know. This did eventually get deployed.

**Comment by jqno** [comment]
Thanks!
