### ISSUE TITLE
implementation using Haskell/Yesod

### ISSUE THREAD

**Issue by moredip** [TodoBackend/todo-backend-site#25]

**Comment by FranklinChen** [comment]
Might try this, unless someone beats me to it.

**Comment by moredip** [comment]
Please do! And if someone else beats you to it we'll just have two implementations :)

**Comment by moredip** [comment]
PR #36 provides a Haskell/Scotty implementation, but the field is still wide open for a Yesod contribution

**Comment by jhedev** [comment]
I have also a working [implementation](https://github.com/jhedev/todobackend-servant) using Haskell/[Servant](http://haskell-servant.github.io/), but still need to deploy it somewhere.

**Comment by moredip** [comment]
Resolved by #43
