### ISSUE TITLE
Implementation using Ratpack

### ISSUE THREAD

**Issue by moredip** [TodoBackend/todo-backend-site#63]
https://ratpack.io/

**Comment by moredip** [comment]
Popped a request into Ratpack's issues: https://github.com/ratpack/ratpack/issues/919

**Comment by danhyun** [comment]
Sounds like fun :)

**Comment by danhyun** [comment]
got something working here http://todobackend.com/client/index.html?https://todo-backend-ratpack-java.herokuapp.com/todo, will update with repo later

**Comment by danhyun** [comment]
Preliminary source up here:

https://github.com/danhyun/todo-backend-ratpack-java

**Comment by danhyun** [comment]
The implementation is ready to go, what else needs to be done?

**Comment by moredip** [comment]
@danhyun I just noticed this never got added to the site, so I did it myself in 9340d7ec9eef95034170b4b4125944f5f2ca59f3. Take a look and make sure you're ok with the description etc.
